CREATE TABLE `user` (
	`no`	BIGINT	NOT NULL	COMMENT 'PK',
	`id`	VARCHAR(255)	NOT NULL	COMMENT 'UK',
	`username`	VARCHAR(100)	NOT NULL	COMMENT '아이디',
	`password`	VARCHAR(255)	NOT NULL	COMMENT '비밀번호',
	`email`	VARCHAR(255)	NULL	COMMENT '이메일',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '이름',
	`enabled`	INT	NULL	DEFAULT 1	COMMENT '활성화여부',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
);